name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Octave
        run: |
          sudo apt-get update
          sudo apt-get install -y octave

      - name: Run smoke tests (Octave)
        run: |
          cd tests
          octave --quiet --eval "addpath(genpath('..')); run_ci"
